---
- name: Log 서버 구축
  hosts: logserver
  vars:
    # Graylog vars
    graylog_version: 6.1
    graylog_install_java: True
    # Insert your own here. Generate with: pwgen -s 96 1
    graylog_password_secret: "u0kNoJlVTQXyfherJ8BP7pOcsrCzWoNhQPDTa3njlqGl3QayuoY07IcPIGGZ4FF2RZ1MkWdHsgdVFoNKoN8rAtmj9vq4Q732"
    # Insert your own root_password_sha2 here.
    graylog_root_password_sha2: "135698ee5b39ac9515ae9c03ff0d9525bb1dcdd50824b4aa97a8e20c9e3eb2a7"
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_install_open_package: True
    graylog_install_enterprise_package: False
  tasks:
    - name: 저장소 등록 - MongoDB
      ansible.builtin.yum_repository:
        name: mongodb-org-6.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
        gpgcheck: no
        enabled: true

    - name: 패키지 설치 - mongodb-org
      ansible.builtin.include_tasks: tasks/install_pkg.yml
      vars: 
        package: mongodb-org

    - name: 서비스 기동 - mongod
      ansible.builtin.include_tasks: tasks/start_svc.yml
      vars: 
        svc: mongod
    
    - name: GPG Key 등록 - Elasticsearch
      ansible.builtin.rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    
    - name: 저장소 등록 - Elasticsearch
      ansible.builtin.yum_repository:
        name: elasticsearch-7.x
        description: Elasticsearch repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
        enabled: yes
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        repo_gpgcheck: no

    - name: 패키지 설치 - elasticsearch-oss 
      ansible.builtin.include_tasks: tasks/install_pkg.yml
      vars: 
        package: elasticsearch-oss 
      
    - name: 서비스 설정 - /etc/elasticsearch/elasticsearch.yml
      ansible.builtin.template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'

    - name: 서비스 기동 - elasticsearch
      ansible.builtin.include_tasks: tasks/start_svc.yml
      vars: 
        svc: elasticsearch

    - name: 패키지 설치 - java-1.8.0-openjdk java-1.8.0-openjdk-devel
      ansible.builtin.include_tasks: tasks/install_pkg.yml
      vars: 
        package:
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
    
    - name: Role - graylog2.graylog
      ansible.builtin.include_role:
        name: roles/graylog2.graylog
      tags:
        - "graylog"
    
    - name: 방화벽 포트 등록
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - 9000/tcp
        - 1514/tcp
        - 1514/udp
