---
# tasks file for dns
- name: 1. 패키지 설치 - bind, bind-utils
  ansible.builtin.dnf:
    name: bind, bind-utils
    state: present

- name: 2. 서비스 설정- /etc/named.conf(j2)
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/named-checkconf %s
  

- name: 2. 서비스 설정- /etc/named.rfc1912.zones(j2)
  ansible.builtin.template:
    src: named.rfc1912.zones.j2
    dest: /etc/named.rfc1912.zones
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/named-checkconf %s

- name: 3. 정방향 존 파일 생성 - /var/named/{{ domain }}.zone
  ansible.builtin.template:
    src: zone.j2
    dest: "/var/named/{{ domain }}.zone"
    owner: root
    group: root
    mode: '0644'
    validate: "named-checkzone {{ domain }} %s"
  notify: Restart named

- name: 3. 메일 정방향 존 파일 생성
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
    validate: "named-checkzone {{ item.temp }} %s"
  loop:
    - src: mail/mail06.zone.j2
      dest: "/var/named/{{ mail06_domain }}.zone"
      temp: "{{ mail06_domain }}"
    - src: mail/mail07.zone.j2
      dest: "/var/named/{{ mail07_domain }}.zone"
      temp: "{{ mail07_domain }}"

- name: Restart named
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: true

- name: 4. 방화벽 포트 등록 - dns
  ansible.posix.firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled
