---
- name: Start tomcat
  ansible.builtin.systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
